
----

In [3]:
import pandas as pd
data = pd.read_csv('cursos-prouni.csv')
data.head()

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,cidade_filtro,universidade_nome,campus_nome,campus_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,NTAwMjAwNDAyNzA0,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,706710,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Enfermagem,663.36,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,MzUxNTA2MTUwMzA4,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,1002328,Medicina,739.62,738.08,738.96,718.64
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Psicologia,651.00,652.22,NaN,NaN
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,MTIwMjAwNDAwNDAx,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,658996,Medicina,758.32,723.94,734.92,711.26

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41447 entries, 0 to 41446
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   grau                  41447 non-null  object
 1   turno                 41447 non-null  object
 2   mensalidade           41447 non-null  float64
 3   bolsa_integral_cotas  32520 non-null  float64
 4   bolsa_integral_ampla  25404 non-null  float64
 5   bolsa_parcial_cotas   8828 non-null   float64
 6   bolsa_parcial_ampla   13041 non-null  float64
 7   curso_id              41447 non-null  int64
 8   curso_busca           41447 non-null  object
 9   cidade_busca          41447 non-null  object
 10  uf_busca              41447 non-null  object
 11  cidade_filtro         41447 non-null  object
 12  universidade_nome     41447 non-null  object
 13  campus_nome           41447 non-null  object
 14  campus_id             41447 non-null  int64
 15  nome                  41447 non-null  object
 16  nota_integral_ampla   32520 non-null  float64
 17  nota_integral_cotas   16802 non-null  float64
 18  nota_parcial_ampla    16350 non-null  float64
 19  nota_parcial_cotas    5519 non-null   float64
dtypes: float64(9), int64(2), object(9)
memory usage: 6.3+ MB

In [5]:
data.describe()

,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,campus_id,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
count,41447.000000,32520.000000,25404.000000,8828.000000,13041.000000,4.144700e+04,4.144700e+04,32520.000000,16802.000000,16350.000000,5519.000000
mean,622.636966,1.535394,2.513541,1.873018,8.632544,4.207360e+13,6.786530e+05,575.982999,564.470439,527.517136,511.799638
std,606.442296,2.191578,3.019549,2.336403,18.372991,6.061552e+13,6.398410e+05,57.827594,57.869145,60.202170,56.787140
min,139.000000,0.000000,1.000000,1.000000,1.000000,2.248801e+07,2.240000e+02,450.000000,450.000000,450.000000,450.000000
25%,278.000000,0.000000,1.000000,1.000000,1.000000,6.460131e+11,1.172300e+04,544.360000,532.865000,453.980000,450.000000
50%,393.350000,1.000000,1.000000,1.000000,2.000000,2.003572e+12,6.587550e+05,580.740000,571.450000,532.420000,511.820000
75%,825.000000,2.000000,3.000000,2.000000,6.000000,1.036636e+14,1.058794e+06,614.145000,603.315000,573.235000,557.170000
max,9999.990000,58.000000,67.000000,74.000000,350.000000,2.008632e+14,2.008633e+06,781.200000,792.240000,776.360000,768.340000

In [6]:
data.head()

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,cidade_filtro,universidade_nome,campus_nome,campus_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,NTAwMjAwNDAyNzA0,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,706710,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Enfermagem,663.36,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,MzUxNTA2MTUwMzA4,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,1002328,Medicina,739.62,738.08,738.96,718.64
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Psicologia,651.00,652.22,NaN,NaN
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,MTIwMjAwNDAwNDAx,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,658996,Medicina,758.32,723.94,734.92,711.26

In [9]:
data["mensalidade"].unique()

array([9999.99, 9836.4 , 9715.61, ...,  149.  ,  144.  ,  139.  ])

In [10]:
data["nota_integral_ampla"].unique()

array([740.22, 663.36, 739.62, ..., 484.84, 504.18, 502.36])